// IMPLEMENTATION DONE (DO NOT EDIT THIS FILE ANYMORE)

import { button as buttonStyles } from "@heroui/theme";
import DefaultLayout from "@/layouts/default";
import { Image, Button } from "@heroui/react";
import { Input } from "@heroui/input";
import { FaCamera, FaExclamationTriangle, FaSpinner } from "react-icons/fa";
import { useEffect, useState } from "react";
import { UserData } from "@/api/interface";
import { auth_user } from "@/api/auth_user";
import { API_URL } from "@/api/endpoint";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useNavigate } from "react-router-dom";

export default function ProfilPage() {
  const [initialLoading, setInitialLoading] = useState(true);
  const [isEditing, setIsEditing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);
  const [showCancelConfirm, setShowCancelConfirm] = useState(false);
  const [imageUploading, setImageUploading] = useState(false);
  const [email, setEmail] = useState("");
  const navigate = useNavigate();

  // Current data state
  const [userData, setUserData] = useState({
    name: "",
    email: "",
    instance: "",
    profile: "",
    createdAt: "",
  });

  // Checkpoint for original data
  const [originalData, setOriginalData] = useState({
    name: "",
    email: "",
    instance: "",
    profile: "",
    createdAt: "",
  });

  useEffect(() => {
    const hasChanges =
      userData.name !== originalData.name ||
      userData.instance !== originalData.instance ||
      userData.profile !== originalData.profile;
    setHasUnsavedChanges(hasChanges);
  }, [userData, originalData]);

  // Handle keyboard shortcuts for saving and canceling
  useEffect(() => {
    const handleKeyPress = (e: any) => {
      if (e.key === "Escape" && isEditing && !isSaving && !imageUploading) {
        handleCancelClick();
      }
      if (
        e.ctrlKey &&
        e.key === "s" &&
        isEditing &&
        !isSaving &&
        !imageUploading
      ) {
        e.preventDefault();
        handleSave();
      }
    };
    window.addEventListener("keydown", handleKeyPress);
    return () => window.removeEventListener("keydown", handleKeyPress);
  }, [isEditing, hasUnsavedChanges, isSaving, imageUploading]);

  const fetchUserData = async () => {
    try {
      setInitialLoading(true);
      const response = await auth_user.get_current_user();

      if (response.success && response.data) {
        const user_data_object = response.data as UserData;

        const initData = {
          name: user_data_object.UserFullName,
          email: user_data_object.UserEmail,
          instance: user_data_object.UserInstance,
          profile:
            user_data_object.UserPicture ||
            "https://i.pravatar.cc/150?u=a042581f4e29026704d",
          createdAt: user_data_object.UserCreatedAt,
        };

        setEmail(user_data_object.UserEmail);
        setUserData(initData);
        setOriginalData(initData);
      } else {
        toast.error(response.message || "Failed to fetch user data", {
          toastId: "profile-error",
        });
      }
    } catch (error) {
      toast.error("Unexpected error while fetching user data!", {
        toastId: "profile-fetch-error",
      });
    } finally {
      setInitialLoading(false);
    }
  };

  useEffect(() => {
    fetchUserData();
  }, []);

  const handleSave = async () => {
    if (!isEditing || isSaving || imageUploading) return;

    const trimmedName = userData.name.trim();
    const trimmedInstance = userData.instance.trim();

    if (!trimmedName) {
      toast.info("Name cannot be empty", { toastId: "profile-info" });
      return;
    }

    if (trimmedName.length < 2) {
      toast.info("Name must be at least 2 characters long", {
        toastId: "profile-info",
      });
      return;
    }

    if (!trimmedInstance) {
      toast.info("Instance cannot be empty", { toastId: "profile-info" });
      return;
    }

    if (!hasUnsavedChanges) {
      toast.info("No changes detected, nothing to save", {
        toastId: "profile-info",
      });
      setIsEditing(false);
      return;
    }

    try {
      setIsSaving(true);
      const response = await auth_user.user_edit({
        name: trimmedName,
        instance: trimmedInstance,
        picture: userData.profile,
      });

      if (response.success) {
        toast.success("Profile updated successfully!", {
          toastId: "profile-success",
        });
        setIsEditing(false);
      } else {
        toast.error(response.message || "Failed to update profile", {
          toastId: "profile-error",
        });
      }
    } catch (error) {
      toast.error("Network error. Please try again.", {
        toastId: "profile-error-network",
      });
    } finally {
      setIsSaving(false);
    }
  };

  // Handle input changes
  const handleInputChange = (field: string, value: string) => {
    setUserData((prev) => ({
      ...prev,
      [field]: value,
    }));
  };

  // Handle cancel button click
  const handleCancelClick = () => {
    if (isSaving || imageUploading) return;

    if (hasUnsavedChanges) {
      setShowCancelConfirm(true);
    } else {
      setIsEditing(false);
      toast.info("Edit cancelled, no changes were made.", {
        toastId: "edit-canelled",
      });
    }
  };

  // Confirm cancel action
  const handleConfirmCancel = () => {
    setUserData(originalData);
    setIsEditing(false);
    setShowCancelConfirm(false);
    toast.info("Changes discarded, reverting to original data", {
      toastId: "changes-discarded",
    });
  };

  // Handle edit button click
  const handleEditClick = () => {
    if (!isEditing) {
      setIsEditing(true);
      toast.info("You can now edit your profile", { toastId: "edit-profile" });
    }
  };

  const handleImageChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!isEditing || imageUploading) {
      toast.warning(
        "Please enter edit mode first to change your profile picture",
      , {
          toastId: "a"
        });
      e.target.value = "";
      return;
    }

    const file = e.target.files?.[0];
    if (!file) return;

    const maxSizeInBytes = 3 * 1024 * 1024;
    if (file.size > maxSizeInBytes) {
      toast.error("Image size must be less than 3MB", {
          toastId: "a"
        });
      e.target.value = "";
      return;
    }

    const allowedTypes = ["image/jpeg", "image/jpg", "image/png", "image/webp"];
    if (!allowedTypes.includes(file.type)) {
      toast.error("Only JPG, JPEG, PNG, and WebP images are allowed");
      e.target.value = "";
      return;
    }

    setImageUploading(true);
    const reader = new FileReader();

    reader.onloadend = async () => {
      const base64Image = reader.result as string;

      try {
        const response = await auth_user.user_image({ data: base64Image });

        if (response.success) {
          let serverPath = response.data?.filename || "";
          serverPath = serverPath.replace(/^https?:\/\/[^/]+:3000/, API_URL);
          setUserData((prev) => ({ ...prev, profile: serverPath }));
          toast.success("Image uploaded! Remember to save your changes.");
        } else {
          toast.error(response.message || "Failed to upload image");
        }
      } catch (error) {
        toast.error("Error uploading image");
      } finally {
        setImageUploading(false);
        e.target.value = "";
      }
    };

    reader.readAsDataURL(file);
  };

  const handleRemoveImage = async () => {
    if (!isEditing || imageUploading) {
      toast.warning(
        "Please enter edit mode first to remove your profile picture",
      );
      return;
    }

    setUserData((prev) => ({
      ...prev,
      profile: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    }));
    toast.success("Profile picture will be removed when you save changes");
  };

  const handleChangePassword = async () => {
    if (!isEditing || isSaving || imageUploading) return;
    toast.info(
      "Password change functionality is not implemented yet. Please contact support.",
      {
        toastId: "change-password-not-implemented",
      },
    );
    navigate("/change-password/:" + email);
  };

  if (initialLoading) {
    return (
      <DefaultLayout>
        <div className="flex flex-col justify-center items-center min-h-[400px] gap-4">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-500" />
          <p className="text-gray-600">Loading your profile...</p>
        </div>
      </DefaultLayout>
    );
  }

  return (
    <DefaultLayout>
      {/* Cancel Confirmation Modal */}
      {showCancelConfirm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white p-6 rounded-lg shadow-lg max-w-md w-full mx-4">
            <div className="flex items-center gap-3 mb-4">
              <FaExclamationTriangle className="text-yellow-500 text-xl" />
              <h3 className="text-lg font-semibold">Discard Changes?</h3>
            </div>
            <p className="text-gray-600 mb-6">
              You have unsaved changes. Are you sure you want to discard them?
            </p>
            <div className="flex gap-3 justify-end">
              <Button
                className={buttonStyles({
                  color: "default",
                  radius: "full",
                  variant: "bordered",
                  size: "sm",
                })}
                onClick={() => setShowCancelConfirm(false)}
              >
                Keep Editing
              </Button>
              <Button
                className={buttonStyles({
                  color: "danger",
                  radius: "full",
                  variant: "solid",
                  size: "sm",
                })}
                onClick={handleConfirmCancel}
              >
                Discard Changes
              </Button>
            </div>
          </div>
        </div>
      )}

      <section className="flex flex-col lg:flex-row gap-10 p-4 md:p-8">
        {/* Profile Image Section */}
        <div className="order-1 lg:order-2 flex flex-col gap-4 items-center w-full lg:w-auto">
          <div className="relative">
            <Image
              className="rounded-full object-cover pointer-events-none"
              alt="Your Profile"
              src={
                userData.profile ||
                "https://i.pravatar.cc/150?u=a042581f4e29026704d"
              }
              fallbackSrc="https://i.pravatar.cc/150?u=a042581f4e29026704d"
              width={200}
              height={200}
            />
            <label
              className={`absolute -bottom-1 -right-[0px] z-10 rounded-full p-2 transition-colors ${
                isEditing && !imageUploading
                  ? "bg-secondary-500 text-white cursor-pointer hover:bg-secondary-600"
                  : "bg-gray-300 text-gray-500 cursor-not-allowed"
              }`}
              title={
                imageUploading
                  ? "Uploading image..."
                  : isEditing
                    ? "Change profile picture"
                    : "Enter edit mode to change picture"
              }
            >
              {imageUploading ? (
                <FaSpinner className="w-5 h-5 animate-spin" />
              ) : (
                <FaCamera className="w-5 h-5" />
              )}
              <input
                type="file"
                accept="image/*"
                onChange={handleImageChange}
                className="hidden"
                disabled={!isEditing || imageUploading}
              />
            </label>
          </div>

          <Button
            className={
              buttonStyles({
                color: "danger",
                radius: "full",
                variant: "solid",
                size: "sm",
              }) +
              " " +
              (!isEditing ? "invisible pointer-events-none" : "")
            }
            onClick={handleRemoveImage}
            isDisabled={imageUploading}
          >
            Remove Image
          </Button>

          <div className="w-full">
            <Input
              color="secondary"
              label="Member Since"
              type="text"
              variant="flat"
              readOnly
              value={
                userData.createdAt
                  ? new Date(userData.createdAt).toLocaleDateString("en-US", {
                      year: "numeric",
                      month: "long",
                      day: "numeric",
                    })
                  : "-"
              }
            />
          </div>
        </div>

        {/* Form Section */}
        <div className="order-2 lg:order-1 flex flex-wrap gap-4 w-full lg:w-[700px]">
          <div className="flex items-center gap-2 w-full">
            <p className="text-blue-600 font-semibold text-sm">
              {isEditing ? `Editing Your Profile` : `Your Profile`}
            </p>
            {hasUnsavedChanges && isEditing && (
              <span className="text-orange-500 text-xs font-medium">
                • Unsaved changes
              </span>
            )}
            {imageUploading && (
              <span className="text-blue-500 text-xs font-medium">
                • Uploading image...
              </span>
            )}
          </div>

          <Input
            color="secondary"
            label={`Full Name ${hasUnsavedChanges && userData.name !== originalData.name ? "*" : ""}`}
            type="text"
            variant="flat"
            className="w-full"
            value={userData.name}
            onChange={(e) => handleInputChange("name", e.target.value)}
            {...(!isEditing && { readOnly: true })}
            isRequired
          />

          <Input
            color="secondary"
            label="Email Address"
            type="email"
            variant="flat"
            className="w-full"
            value={userData.email}
            readOnly
            description="Email cannot be changed"
          />

          <Input
            color="secondary"
            label={`Instance/Organization ${hasUnsavedChanges && userData.instance !== originalData.instance ? "*" : ""}`}
            type="text"
            variant="flat"
            className="w-full"
            value={userData.instance}
            onChange={(e) => handleInputChange("instance", e.target.value)}
            {...(!isEditing && { readOnly: true })}
            isRequired
          />

          {hasUnsavedChanges &&
            userData.profile !== originalData.profile &&
            isEditing && (
              <div className="w-full">
                <p className="text-orange-500 text-xs font-medium">
                  • Profile picture changed - remember to save your changes
                </p>
              </div>
            )}

          <div className="flex flex-col sm:flex-row justify-center md:justify-start gap-2 sm:gap-4 pt-4 w-full">
            {isEditing ? (
              <Button
                className={buttonStyles({
                  color: "secondary",
                  radius: "full",
                  variant: "solid",
                  size: "sm",
                })}
                onClick={handleCancelClick}
                isDisabled={isSaving || imageUploading}
              >
                Cancel
              </Button>
            ) : (
              <Button
                className={buttonStyles({
                  color: "secondary",
                  radius: "full",
                  variant: "solid",
                  size: "sm",
                })}
                onClick={handleEditClick}
                isDisabled={imageUploading}
              >
                Edit Profile
              </Button>
            )}

            <Button
              className={buttonStyles({
                color: "secondary",
                radius: "full",
                variant: isEditing ? "solid" : "bordered",
                size: "sm",
              })}
              onClick={handleSave}
              isLoading={isSaving}
            >
              {isSaving ? "Saving..." : "Save Changes"}
            </Button>

            <Button
              className={buttonStyles({
                color: "secondary",
                radius: "full",
                variant: isEditing ? "solid" : "bordered",
                size: "sm",
              })}
              onClick={handleChangePassword}
            >
              Change Password
            </Button>

            {!isEditing && (
              <span className="text-xs text-gray-500 ml-2 self-center">
                Enter edit mode to enable
              </span>
            )}
          </div>
        </div>
        <ToastContainer />
      </section>
    </DefaultLayout>
  );
}
